# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 561)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("font: 12pt \"Fixedsys\";\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 10, 311, 471))
        self.textBrowser.setStyleSheet("color: rgb(102, 102, 153);\n"
"border: 1px solid #CCCCCC\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 490, 221, 16))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(530, 350, 231, 131))
        self.frame.setStyleSheet("font: 12pt \"Fixedsys\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_SetT = QtWidgets.QPushButton(self.frame)
        self.pushButton_SetT.setGeometry(QtCore.QRect(70, 70, 101, 51))
        self.pushButton_SetT.setObjectName("pushButton_SetT")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_2.setStyleSheet("font: 12pt \"Fixedsys\";")
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName("label_2")
        self.lineEdit_InputT = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_InputT.setGeometry(QtCore.QRect(110, 20, 91, 21))
        self.lineEdit_InputT.setText("")
        self.lineEdit_InputT.setObjectName("lineEdit_InputT")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 20, 21, 16))
        self.label_3.setStyleSheet("font: 12pt \"Fixedsys\";")
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 10, 391, 241))
        self.frame_2.setStyleSheet("border: 1px solid #CCCCCC\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_instruction = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_instruction.setGeometry(QtCore.QRect(150, 170, 221, 31))
        self.lineEdit_instruction.setText("")
        self.lineEdit_instruction.setObjectName("lineEdit_instruction")
        self.pushButton_instruction = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_instruction.setGeometry(QtCore.QRect(30, 170, 93, 28))
        self.pushButton_instruction.setStyleSheet("color: rgb(102, 102, 153);\n"
"background-color: rgb(204, 204, 204);\n"
"border: 1px solid #CCCCCC\n"
"")
        self.pushButton_instruction.setObjectName("pushButton_instruction")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(150, 70, 221, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 361, 20))
        self.label_4.setStyleSheet("border: 0px solid #CCCCCC\n"
"")
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 70, 121, 41))
        self.frame_3.setStyleSheet("font: 10pt \"Fixedsys\";\n"
"border: 0px solid #CCCCCC\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_6.setObjectName("label_6")
        self.graphicsView_avatar = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_avatar.setGeometry(QtCore.QRect(370, 350, 131, 131))
        self.graphicsView_avatar.setObjectName("graphicsView_avatar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 290, 401, 20))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 26))
        self.menubar.setObjectName("menubar")
        self.menuSteins_Gate = QtWidgets.QMenu(self.menubar)
        self.menuSteins_Gate.setObjectName("menuSteins_Gate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSteins_Gate.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Current temperature/℃"))
        self.pushButton_SetT.setText(_translate("MainWindow", "SET T"))
        self.label_2.setText(_translate("MainWindow", "Input T:"))
        self.label_3.setText(_translate("MainWindow", "℃"))
        self.pushButton_instruction.setText(_translate("MainWindow", "Input"))
        self.label_4.setText(_translate("MainWindow", "Sending Customized Instruction Area"))
        self.label_5.setText(_translate("MainWindow", "Returned"))
        self.label_6.setText(_translate("MainWindow", "from TU-20D"))
        self.label_7.setText(_translate("MainWindow", "☆——————————————————★"))
        self.menuSteins_Gate.setTitle(_translate("MainWindow", "TU-20D Software氵"))
